/* 
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Algorand.Client.SwaggerDateConverter;

namespace Algorand.V2.Model
{
    /// <summary>
    /// \\[apan\\] defines the what additional actions occur with the transaction.  Valid types: * noop * optin * closeout * clear * update * update * delete
    /// </summary>
    /// <value>\\[apan\\] defines the what additional actions occur with the transaction.  Valid types: * noop * optin * closeout * clear * update * update * delete</value>
    //[JsonConverter(typeof(StringEnumConverter))]
    public enum OnCompletion
    {
        /// <summary>
        /// Enum Noop for value: noop
        /// </summary>
        [EnumMember(Value = "noop")]
        Noop = 0,
        /// <summary>
        /// Enum Optin for value: optin
        /// </summary>
        [EnumMember(Value = "optin")]
        Optin = 1,
        /// <summary>
        /// Enum Closeout for value: closeout
        /// </summary>
        [EnumMember(Value = "closeout")]
        Closeout = 2,
        /// <summary>
        /// Enum Clear for value: clear
        /// </summary>
        [EnumMember(Value = "clear")]
        Clear = 3,
        /// <summary>
        /// Enum Update for value: update
        /// </summary>
        [EnumMember(Value = "update")]
        Update = 4,
        /// <summary>
        /// Enum Delete for value: delete
        /// </summary>
        [EnumMember(Value = "delete")]
        Delete = 5
    }
}
