/* 
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Algorand.Kmd.Client.Api;
using Algorand.Kmd.Client.Model;
using Algorand.Kmd.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing APIV1POSTMultisigExportResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class APIV1POSTMultisigExportResponseTests
    {
        // TODO uncomment below to declare an instance variable for APIV1POSTMultisigExportResponse
        //private APIV1POSTMultisigExportResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of APIV1POSTMultisigExportResponse
            //instance = new APIV1POSTMultisigExportResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of APIV1POSTMultisigExportResponse
        /// </summary>
        [Test]
        public void APIV1POSTMultisigExportResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" APIV1POSTMultisigExportResponse
            //Assert.IsInstanceOfType<APIV1POSTMultisigExportResponse> (instance, "variable 'instance' is a APIV1POSTMultisigExportResponse");
        }


        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Test]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'MultisigVersion'
        /// </summary>
        [Test]
        public void MultisigVersionTest()
        {
            // TODO unit test for the property 'MultisigVersion'
        }
        /// <summary>
        /// Test the property 'Pks'
        /// </summary>
        [Test]
        public void PksTest()
        {
            // TODO unit test for the property 'Pks'
        }
        /// <summary>
        /// Test the property 'Threshold'
        /// </summary>
        [Test]
        public void ThresholdTest()
        {
            // TODO unit test for the property 'Threshold'
        }

    }

}
