/* 
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Algorand.Kmd.Client.Api;
using Algorand.Kmd.Client.Model;
using Algorand.Kmd.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Ed25519Signature
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Ed25519SignatureTests
    {
        // TODO uncomment below to declare an instance variable for Ed25519Signature
        //private Ed25519Signature instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Ed25519Signature
            //instance = new Ed25519Signature();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Ed25519Signature
        /// </summary>
        [Test]
        public void Ed25519SignatureInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Ed25519Signature
            //Assert.IsInstanceOfType<Ed25519Signature> (instance, "variable 'instance' is a Ed25519Signature");
        }



    }

}
