/* 
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Algorand.Kmd.Client.Api;
using Algorand.Kmd.Client.Model;
using Algorand.Kmd.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ListMultisigRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ListMultisigRequestTests
    {
        // TODO uncomment below to declare an instance variable for ListMultisigRequest
        //private ListMultisigRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListMultisigRequest
            //instance = new ListMultisigRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListMultisigRequest
        /// </summary>
        [Test]
        public void ListMultisigRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ListMultisigRequest
            //Assert.IsInstanceOfType<ListMultisigRequest> (instance, "variable 'instance' is a ListMultisigRequest");
        }


        /// <summary>
        /// Test the property 'WalletHandleToken'
        /// </summary>
        [Test]
        public void WalletHandleTokenTest()
        {
            // TODO unit test for the property 'WalletHandleToken'
        }

    }

}
