/* 
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Algorand.Kmd.Client.Api;
using Algorand.Kmd.Client.Model;
using Algorand.Kmd.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MultisigSig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MultisigSigTests
    {
        // TODO uncomment below to declare an instance variable for MultisigSig
        //private MultisigSig instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MultisigSig
            //instance = new MultisigSig();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MultisigSig
        /// </summary>
        [Test]
        public void MultisigSigInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MultisigSig
            //Assert.IsInstanceOfType<MultisigSig> (instance, "variable 'instance' is a MultisigSig");
        }


        /// <summary>
        /// Test the property 'Subsigs'
        /// </summary>
        [Test]
        public void SubsigsTest()
        {
            // TODO unit test for the property 'Subsigs'
        }
        /// <summary>
        /// Test the property 'Threshold'
        /// </summary>
        [Test]
        public void ThresholdTest()
        {
            // TODO unit test for the property 'Threshold'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }

    }

}
