/* 
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Algorand.Kmd.Client.Api;
using Algorand.Kmd.Client.Model;
using Algorand.Kmd.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MultisigSubsig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MultisigSubsigTests
    {
        // TODO uncomment below to declare an instance variable for MultisigSubsig
        //private MultisigSubsig instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MultisigSubsig
            //instance = new MultisigSubsig();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MultisigSubsig
        /// </summary>
        [Test]
        public void MultisigSubsigInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MultisigSubsig
            //Assert.IsInstanceOfType<MultisigSubsig> (instance, "variable 'instance' is a MultisigSubsig");
        }


        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Test]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Sig'
        /// </summary>
        [Test]
        public void SigTest()
        {
            // TODO unit test for the property 'Sig'
        }

    }

}
