/* 
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Algorand.Kmd.Client.Api;
using Algorand.Kmd.Client.Model;
using Algorand.Kmd.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PublicKey
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PublicKeyTests
    {
        // TODO uncomment below to declare an instance variable for PublicKey
        //private PublicKey instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PublicKey
            //instance = new PublicKey();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PublicKey
        /// </summary>
        [Test]
        public void PublicKeyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PublicKey
            //Assert.IsInstanceOfType<PublicKey> (instance, "variable 'instance' is a PublicKey");
        }



    }

}
