/* 
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Algorand.Kmd.Client.Api;
using Algorand.Kmd.Client.Model;
using Algorand.Kmd.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RenameWalletRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RenameWalletRequestTests
    {
        // TODO uncomment below to declare an instance variable for RenameWalletRequest
        //private RenameWalletRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RenameWalletRequest
            //instance = new RenameWalletRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RenameWalletRequest
        /// </summary>
        [Test]
        public void RenameWalletRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RenameWalletRequest
            //Assert.IsInstanceOfType<RenameWalletRequest> (instance, "variable 'instance' is a RenameWalletRequest");
        }


        /// <summary>
        /// Test the property 'WalletId'
        /// </summary>
        [Test]
        public void WalletIdTest()
        {
            // TODO unit test for the property 'WalletId'
        }
        /// <summary>
        /// Test the property 'WalletName'
        /// </summary>
        [Test]
        public void WalletNameTest()
        {
            // TODO unit test for the property 'WalletName'
        }
        /// <summary>
        /// Test the property 'WalletPassword'
        /// </summary>
        [Test]
        public void WalletPasswordTest()
        {
            // TODO unit test for the property 'WalletPassword'
        }

    }

}
