/* 
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Algorand.Kmd.Client.Api;
using Algorand.Kmd.Client.Model;
using Algorand.Kmd.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SignTransactionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SignTransactionRequestTests
    {
        // TODO uncomment below to declare an instance variable for SignTransactionRequest
        //private SignTransactionRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SignTransactionRequest
            //instance = new SignTransactionRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SignTransactionRequest
        /// </summary>
        [Test]
        public void SignTransactionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SignTransactionRequest
            //Assert.IsInstanceOfType<SignTransactionRequest> (instance, "variable 'instance' is a SignTransactionRequest");
        }


        /// <summary>
        /// Test the property 'Transaction'
        /// </summary>
        [Test]
        public void TransactionTest()
        {
            // TODO unit test for the property 'Transaction'
        }
        /// <summary>
        /// Test the property 'TransactionType'
        /// </summary>
        [Test]
        public void TransactionTypeTest()
        {
            // TODO unit test for the property 'TransactionType'
        }
        /// <summary>
        /// Test the property 'WalletHandleToken'
        /// </summary>
        [Test]
        public void WalletHandleTokenTest()
        {
            // TODO unit test for the property 'WalletHandleToken'
        }
        /// <summary>
        /// Test the property 'WalletPassword'
        /// </summary>
        [Test]
        public void WalletPasswordTest()
        {
            // TODO unit test for the property 'WalletPassword'
        }

    }

}
