/* 
 * Algod REST API.
 *
 * API Endpoint for AlgoD Operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Algorand.Algod.Client.Api;
using Algorand.Algod.Client.Model;
using Algorand.Algod.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AssetList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AssetListTests
    {
        // TODO uncomment below to declare an instance variable for AssetList
        //private AssetList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AssetList
            //instance = new AssetList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AssetList
        /// </summary>
        [Test]
        public void AssetListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AssetList
            //Assert.IsInstanceOfType<AssetList> (instance, "variable 'instance' is a AssetList");
        }


        /// <summary>
        /// Test the property 'Assets'
        /// </summary>
        [Test]
        public void AssetsTest()
        {
            // TODO unit test for the property 'Assets'
        }

    }

}
