/* 
 * Algod REST API.
 *
 * API Endpoint for AlgoD Operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Algorand.Algod.Client.Api;
using Algorand.Algod.Client.Model;
using Algorand.Algod.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AssetTransferTransactionType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AssetTransferTransactionTypeTests
    {
        // TODO uncomment below to declare an instance variable for AssetTransferTransactionType
        //private AssetTransferTransactionType instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AssetTransferTransactionType
            //instance = new AssetTransferTransactionType();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AssetTransferTransactionType
        /// </summary>
        [Test]
        public void AssetTransferTransactionTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AssetTransferTransactionType
            //Assert.IsInstanceOfType<AssetTransferTransactionType> (instance, "variable 'instance' is a AssetTransferTransactionType");
        }


        /// <summary>
        /// Test the property 'Amt'
        /// </summary>
        [Test]
        public void AmtTest()
        {
            // TODO unit test for the property 'Amt'
        }
        /// <summary>
        /// Test the property 'Closeto'
        /// </summary>
        [Test]
        public void ClosetoTest()
        {
            // TODO unit test for the property 'Closeto'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Rcv'
        /// </summary>
        [Test]
        public void RcvTest()
        {
            // TODO unit test for the property 'Rcv'
        }
        /// <summary>
        /// Test the property 'Snd'
        /// </summary>
        [Test]
        public void SndTest()
        {
            // TODO unit test for the property 'Snd'
        }

    }

}
