/* 
 * Algod REST API.
 *
 * API Endpoint for AlgoD Operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Algorand.Algod.Client.Api;
using Algorand.Algod.Client.Model;
using Algorand.Algod.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AssetParams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AssetParamsTests
    {
        // TODO uncomment below to declare an instance variable for AssetParams
        //private AssetParams instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AssetParams
            //instance = new AssetParams();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AssetParams
        /// </summary>
        [Test]
        public void AssetParamsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AssetParams
            //Assert.IsInstanceOfType<AssetParams> (instance, "variable 'instance' is a AssetParams");
        }


        /// <summary>
        /// Test the property 'Assetname'
        /// </summary>
        [Test]
        public void AssetnameTest()
        {
            // TODO unit test for the property 'Assetname'
        }
        /// <summary>
        /// Test the property 'Clawbackaddr'
        /// </summary>
        [Test]
        public void ClawbackaddrTest()
        {
            // TODO unit test for the property 'Clawbackaddr'
        }
        /// <summary>
        /// Test the property 'Creator'
        /// </summary>
        [Test]
        public void CreatorTest()
        {
            // TODO unit test for the property 'Creator'
        }
        /// <summary>
        /// Test the property 'Defaultfrozen'
        /// </summary>
        [Test]
        public void DefaultfrozenTest()
        {
            // TODO unit test for the property 'Defaultfrozen'
        }
        /// <summary>
        /// Test the property 'Freezeaddr'
        /// </summary>
        [Test]
        public void FreezeaddrTest()
        {
            // TODO unit test for the property 'Freezeaddr'
        }
        /// <summary>
        /// Test the property 'Managerkey'
        /// </summary>
        [Test]
        public void ManagerkeyTest()
        {
            // TODO unit test for the property 'Managerkey'
        }
        /// <summary>
        /// Test the property 'Metadatahash'
        /// </summary>
        [Test]
        public void MetadatahashTest()
        {
            // TODO unit test for the property 'Metadatahash'
        }
        /// <summary>
        /// Test the property 'Reserveaddr'
        /// </summary>
        [Test]
        public void ReserveaddrTest()
        {
            // TODO unit test for the property 'Reserveaddr'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Test]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
        /// <summary>
        /// Test the property 'Unitname'
        /// </summary>
        [Test]
        public void UnitnameTest()
        {
            // TODO unit test for the property 'Unitname'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
