/* 
 * Algod REST API.
 *
 * API Endpoint for AlgoD Operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Algorand.Algod.Client.Api;
using Algorand.Algod.Client.Model;
using Algorand.Algod.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PaymentTransactionType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PaymentTransactionTypeTests
    {
        // TODO uncomment below to declare an instance variable for PaymentTransactionType
        //private PaymentTransactionType instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PaymentTransactionType
            //instance = new PaymentTransactionType();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PaymentTransactionType
        /// </summary>
        [Test]
        public void PaymentTransactionTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PaymentTransactionType
            //Assert.IsInstanceOfType<PaymentTransactionType> (instance, "variable 'instance' is a PaymentTransactionType");
        }


        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Close'
        /// </summary>
        [Test]
        public void CloseTest()
        {
            // TODO unit test for the property 'Close'
        }
        /// <summary>
        /// Test the property 'Closeamount'
        /// </summary>
        [Test]
        public void CloseamountTest()
        {
            // TODO unit test for the property 'Closeamount'
        }
        /// <summary>
        /// Test the property 'Closerewards'
        /// </summary>
        [Test]
        public void CloserewardsTest()
        {
            // TODO unit test for the property 'Closerewards'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Test]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
        /// <summary>
        /// Test the property 'Torewards'
        /// </summary>
        [Test]
        public void TorewardsTest()
        {
            // TODO unit test for the property 'Torewards'
        }

    }

}
