/* 
 * Algod REST API.
 *
 * API Endpoint for AlgoD Operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Algorand.Algod.Client.Api;
using Algorand.Algod.Client.Model;
using Algorand.Algod.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Supply
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SupplyTests
    {
        // TODO uncomment below to declare an instance variable for Supply
        //private Supply instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Supply
            //instance = new Supply();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Supply
        /// </summary>
        [Test]
        public void SupplyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Supply
            //Assert.IsInstanceOfType<Supply> (instance, "variable 'instance' is a Supply");
        }


        /// <summary>
        /// Test the property 'OnlineMoney'
        /// </summary>
        [Test]
        public void OnlineMoneyTest()
        {
            // TODO unit test for the property 'OnlineMoney'
        }
        /// <summary>
        /// Test the property 'Round'
        /// </summary>
        [Test]
        public void RoundTest()
        {
            // TODO unit test for the property 'Round'
        }
        /// <summary>
        /// Test the property 'TotalMoney'
        /// </summary>
        [Test]
        public void TotalMoneyTest()
        {
            // TODO unit test for the property 'TotalMoney'
        }

    }

}
