/* 
 * Algod REST API.
 *
 * API Endpoint for AlgoD Operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Algorand.Algod.Client.Api;
using Algorand.Algod.Client.Model;
using Algorand.Algod.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Version
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VersionTests
    {
        // TODO uncomment below to declare an instance variable for Version
        //private Version instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Version
            //instance = new Version();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Version
        /// </summary>
        [Test]
        public void VersionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Version
            //Assert.IsInstanceOfType<Version> (instance, "variable 'instance' is a Version");
        }


        /// <summary>
        /// Test the property 'Build'
        /// </summary>
        [Test]
        public void BuildTest()
        {
            // TODO unit test for the property 'Build'
        }
        /// <summary>
        /// Test the property 'GenesisHashB64'
        /// </summary>
        [Test]
        public void GenesisHashB64Test()
        {
            // TODO unit test for the property 'GenesisHashB64'
        }
        /// <summary>
        /// Test the property 'GenesisId'
        /// </summary>
        [Test]
        public void GenesisIdTest()
        {
            // TODO unit test for the property 'GenesisId'
        }
        /// <summary>
        /// Test the property 'Versions'
        /// </summary>
        [Test]
        public void VersionsTest()
        {
            // TODO unit test for the property 'Versions'
        }

    }

}
